version: '3.8'

services:
  music-tools-suite:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Mount local directory for file persistence
      - ./downloads:/app/downloads
      # Optional: Mount custom config
      - ./.streamlit:/app/.streamlit
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    container_name: music-tools-suite
    
    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add a reverse proxy for custom domain
# nginx:
#   image: nginx:alpine
#   ports:
#     - "80:80"
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf
#   depends_on:
#     - music-tools-suite
#   restart: unless-stopped 